const GET_PRODUCTS = "GET_PRODUCTS";
const ADD_TO_CART = "ADD_TO_CART";
const PRODUCT_DECREASE = "PRODUCT_DECREASE";
const PRODUCT_INCREASE = "PRODUCT_INCREASE";
const PRODUCT_DELETE = "PRODUCT_DELETE";

export {
  ADD_TO_CART,
  GET_PRODUCTS,
  PRODUCT_DECREASE,
  PRODUCT_DELETE,
  PRODUCT_INCREASE,
};
